# Generated by Django 4.0.4 on 2022-04-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='days_week',
            field=models.ManyToManyField(blank=True, related_name='bbbbbbbbbb', to='medicSearch.dayweek'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aaaaaaaaa', to='medicSearch.neighborhood'),
        ),
    ]
